site_url: https://<username>.github.io/vlarl/
site_name: ??? RL
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 主页
            User Guide: 用户指南
            Algorithm: 算法
            Environment: 环境
            Policy: 策略
            Contributing: 贡献指南
            Get Started: 快速开始
  - exclude:
      glob:
        - '**/sitemap.xml'
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - navigation.instance
    - toc.follow
    - search.suggest
    - search.highlight
nav:
  - Home: index.md

  - User Guide:
      - Overview: user_guide/index.md
      - Get Started: user_guide/get_started.md

  - Algorithm:
      - Overview: algorithm/index.md
      - PPO: algorithm/ppo.md

  - Environment:
      - Overview: env/index.md
      - Libero Environment: env/libero_env.md
      - Custom Environment: env/custom_env.md

  - Policy:
      - Overview: policy/index.md
      - Custom Policy: policy/custom_policy.md

  - Contributing:
      - Overview: contributing/index.md
      - Environment: contributing/env.md
      - Policy: contributing/policy.md
      - Algorithm: contributing/algorithm.md